namespace ProgressGateway.UI.Models
{
    public class StartProcessRequest
    {
        // Unique ID generated by the UI.
        // This is used to identify one specific process execution.
        public string ExecutionId { get; set; }
    }
}
